"""Migrate to more correct datatypes.

Revision ID: 15dab0de5718
Revises: 1e9da2012aed
Create Date: 2024-10-29 13:14:33.372236

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "15dab0de5718"
down_revision: Union[str, None] = "1e9da2012aed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sensor_data", "unique_id")
    op.add_column(
        "sensor_data",
        sa.Column(
            "unique_id",
            sa.Uuid(),
            nullable=False,
        ),
    )
    op.add_column("sensor_table", sa.Column("key", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sensor_table", "key")
    op.alter_column(
        "sensor_data",
        "unique_id",
        existing_type=sa.Uuid(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
